name: screenshot-website

run-name: screenshot-website

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  screenshot-website:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Screenshot Website
        id: screenshot-website
        uses: swinton/screenshot-website@80a97add3949213d227d3366c2309c9ba721f6b5
        with:
          source: https://developer.apple.com/jp/news/
          destination: screenshot.png

      - name: Upload Screenshot to artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: ${{ steps.screenshot-website.outputs.path }}
